# Change these first
owner: FowApps # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website (FowCRM.com)
    url: https://fowcrm.com
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowcrm-logo-circle-transparent.png
  - name: FowAccess
    url: https://access.fowapps.com
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowcrm-logo-circle-transparent.png
  - name: FowCRM
    url: https://crm.fowapps.com
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowcrm-logo-circle-transparent.png
  - name: FowDocs
    url: https://docs.fowapps.com
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowcrm-logo-circle-transparent.png
  - name: Developer Portal
    url: https://developers.fowapps.com
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowcrm-logo-circle-transparent.png
  - name: API Gateway
    url: https://gateway.fowapps.com/health
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowapps-logo-circle-transparent.png
  - name: CRM API
    url: https://gateway.fowapps.com/crm/health
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowapps-logo-circle-transparent.png
  - name: Notification API
    url: https://gateway.fowapps.com/notification/health
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowapps-logo-circle-transparent.png
  - name: Helper API
    url: https://gateway.fowapps.com/helpers/health
    icon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowapps-logo-circle-transparent.png

status-website:
  publish: true
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fowapps.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowapps-logo-circle-transparent.png
  favicon: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowapps-logo-circle-transparent.png
  customHeadHtml: '<script async src="https://www.googletagmanager.com/gtag/js?id=G-46P7B03HRG"></script><script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag("js", new Date());gtag("config", "G-46P7B03HRG");</script>'
  name: FowApps Status Page
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: Welcome
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  responseTime: "0 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
