# Change these first
owner: FowApps # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Website (FowCRM.com)
    url: https://fowcrm.com
  - name: FowAccess
    url: https://access.fowapps.com

status-website:
  publish: true
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fowapps.com
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/FowApps/upptime/master/assets/fowapps-logo-circle-transparent.png
  name: FowApps Status Page
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: Welcome
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
